//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Tomato.Rpc.Packets
{
	public class Void_20Add_28Int32_2C_20Int32_29
	{
		public System.Int32 Arg0;
		public System.Int32 Arg1;
	}
}

