//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Tomato.Rpc.Packets;

namespace Tomato.Rpc.Server
{
	sealed class RpcCalledProxy : global::Tomato.Rpc.Core.IPacketReceiver
	{
		private readonly Tomato.Rpc.Test.Interface.ITest _impl;
		private readonly Dictionary<Type, Action<object>> _packetMethodMap;

		public RpcCalledProxy(Tomato.Rpc.Test.Interface.ITest impl)
		{
			_impl = impl;
			_packetMethodMap = new Dictionary<Type, Action<object>>
			{
				{ typeof(Void_20Add_28Int32_2C_20Int32_29), ProcessVoid_20Add_28Int32_2C_20Int32_29 }
			};
		}

		public void OnReceive(object packet)
		{
			Action<object> processor;
			if(_packetMethodMap.TryGetValue(packet.GetType(), out processor))
				processor(packet);
		}

		void ProcessVoid_20Add_28Int32_2C_20Int32_29(object packetObj)
		{
			var packet = (Void_20Add_28Int32_2C_20Int32_29)packetObj;
			_impl.Add(packet.Arg0, packet.Arg1);
		}
	}
}

