//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Tomato.Rpc.Packets;

namespace Tomato.Rpc.Client
{
	sealed class RpcCallingProxy : Tomato.Rpc.Test.Interface.ITest, global::Tomato.Rpc.Core.IPacketReceiver
	{
		private readonly global::Tomato.Rpc.Core.IPacketSender _packetSender;

		public RpcCallingProxy(global::Tomato.Rpc.Core.IPacketSender packetSender)
		{
			_packetSender = packetSender;
		}

		void global::Tomato.Rpc.Core.IPacketReceiver.OnReceive(object packet)
		{
		}

		public void Add(System.Int32 a, System.Int32 b)
		{
			var packet = new Void_20Add_28Int32_2C_20Int32_29
			{
				Arg0 = a,
				Arg1 = b,
			};
			_packetSender.Send(packet);
		}
	}
}

